### ISSUE TITLE
tests fail on PHP 7.0.19

### ISSUE THREAD

**Issue by fkooman** [delight-im/PHP-Cookie#17]
[Set-Cookie: hello=world; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0]
FAILED: [Set-Cookie: hello=world; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=-1496223363] !== [Set-Cookie: hello=world; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0]

php-7.0.19-1.fc25.x86_64

**Comment by ocram** [comment]
Thank you very much!

The issue that caused this change in behavior in PHP was tracked [here](https://bugs.php.net/bug.php?id=72071) and fixed [here](http://git.php.net/?p=php-src.git;a=commit;h=ba6561d3cc5ef8c2d5a698622586e7aa28e76f5a).

For this library, it seems we must set the `$maxAge` to `\max($maxAge, 0)` if the platform is either of the following:

 * PHP 7.0.x where `x >= 19`
 * PHP 7.1.5+

Do you agree?

**Comment by fkooman** [comment]
```
 max-age-av        = "Max-Age=" non-zero-digit *DIGIT
                       ; In practice, both expires-av and max-age-av
                       ; are limited to dates representable by the
                       ; user agent.
```

So, it is a bit confusing, but it seems `MaxAge=0` would be an illegal value. See also https://tools.ietf.org/html/rfc6265#section-5.2.2 where it is not 100% clear what is actually valid. Seems contradictory.

**Comment by ocram** [comment]
Thanks!

RFC 2109 accepts zero but doesn't accept negative numbers.

RFC 2965 handles this just like its predecessor.

RFC 6265 disallows both negative numbers and zero in its "Server Requirements" but allows both in its "User Agent Requirements".

Anyway, to us, important is what the PHP core does. And since they introduced the change which replaces negative numbers with zero, we should probably do that as well.

**Comment by fkooman** [comment]
Fair enough :)

**Comment by ocram** [comment]
Fixed in https://github.com/delight-im/PHP-Cookie/commit/e81e67a00c30e16888664896b5c864bbdb8245b2. Thanks again!
