### ISSUE TITLE
Why is the Cookie class 'final'?

### ISSUE THREAD

**Issue by MrHaroldA** [delight-im/PHP-Cookie#19]
The Cookie class is defined as final, so it can't be extended anymore. We would like to extend the class with some custom methods but we need to "hack" the "final" declaration before we can do that.

Is there a solid reason the Cookie class is declared as final?

Tnx!

**Comment by ocram** [comment]
Thanks for your feedback!

Sure, there is a reason for this. In general, we're following the principle of *designing* for inheritance, instead of just opening up every single class to be extended and every method to be overridden:

> Design and document for inheritance or else prohibit it
>
> – Joshua Bloch: *Effective Java*

This is not to make anyone’s life harder, of course. Instead, it is to make things simpler for all of us, both developers and users of this library.

Access controls are there for a reason in object-oriented design, and removing `final` everywhere and changing `private` to `protected` everywhere is not really the solution – in general, at least. This may vary between specific cases.

For most people and use cases, there shouldn't really be a need to extend the class, to be honest. And for some use cases, composition instead of inheritance may be the solution.

May we ask what features you’re trying to add? Perhaps this could be useful for all users.

Another major issue why we'd rather not change the current design is that it allows us to iterate more quickly. If we make the `private` methods `protected` or `public` and allow for inheritance, we have a breaking change and need to release a new major version whenever we change something in the signature of those methods.

Right now, we can change those `private` methods in any way we like and the library does not break for anybody who's using it. The same is true for `private` fields. That's a major advantage.

See also:

 * https://martinfowler.com/bliki/DesignedInheritance.html
 * https://kotlinlang.org/docs/reference/classes.html#inheritance
 * https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151221/003897.html

Anyway, that decision is not set in stone. Let’s discuss this, and perhaps removing `final` (and possibly changing method or field visibilities) may be a good thing here.

**Comment by XedinUnknown** [comment]
While it's true that not declaring a class `final` and having all internal properties be `protected` **may** require you to think about internal contracts in a more serious way, this is not necessarily a requirement, as not all methods become an API.

> For most people and use cases, there shouldn't really be a need to extend the class, to be honest.

I don't think that it is the developers' concern how exactly their code will be used. What is a developer's concern, however, is keeping classes open for extension. Who are we to assume whether anyone will or will not need to extend our classes?

IMO some classes may need to be `final`. However, this relates to "leaf" classes, which are called that way because they don't really contain much re-usable logic, but simply tie other logic together. They are made for a very narrow purpose, and relying on their functionality is not safe, because they are often changed without warning. Here, you have only 2 classes, and all the functionality is right inside them. So I don't think that `final` is warranted here.

**Comment by ocram** [comment]
> require you to think about internal contracts in a more serious way, this is not necessarily a requirement, as not all methods become an API.

They do! If we make the class non-final, all `protected` member variables and methods become part of the public API. Right now, there are none. But obviously, you’d want to have some member variables or methods changed from `private` to `protected`, otherwise extending the class does not make so much sense.

> I don't think that it is the developers' concern how exactly their code will be used.

Actually, yes, it *definitely* is! If you *design* a piece of code with thought, in contrast to just dropping some lines into a Gist or Pastebin, thinking about how other developers will use that piece of code is very much your task.

> What is a developer's concern, however, is keeping classes open for extension. Who are we to assume whether anyone will or will not need to extend our classes?

Not really. Extension of classes is one tool in your toolbox. It is not always the best tool to use. The `final` keyword is there for a reason, right? You see, sometimes you *want* to discourage extension.

> However, this relates to "leaf" classes

Yes, such leaf classes are *one* example.

> Here, you have only 2 classes, and all the functionality is right inside them

Exactly! So why should extension be necessary, if all the functionality is right inside the class already? What cookies are and what they can do is defined in technical specifications, so one class can implement all functionality. It’s unlikely that you have custom cookies at your company where they do other things or have new capabilities that regular cookies don’t have.

But I don’t think this discussion leads anywhere.

**Can we please have a more pragmatic discussion here? What are use cases that you encounter in practice where this class does not provide sufficient functionality and you cannot solve the problem with composition (instead of inheritance), either?**

**Comment by XedinUnknown** [comment]
> all protected member variables and methods become part of the public API.

You are the author of the package. Only what you say becomes part of the API. And non-interface methods are definitely not something that is public API by default.

> If you design a piece of code with thought, in contrast to just dropping some lines into a Gist or Pastebin, thinking about how other developers will use that piece of code is very much your task.

Only from the point of view of input/output of your API, but not in terms of _why_ the consumer may want to do something, or _how they would use the results_.

> sometimes you want to discourage extension

When most of your functionality is available via other means, and you have a good reason to discourage extension (can't really think of one, other than leaf classes), then yes. Here, in your repo, you have all functionality locked in the two classes which cannot be extended. This means that their consumer must do things only in the exact way you want them to, and no other way. You say, it's unlikely that a company may want to handle cookies somehow differently. I say, handling cookies in a way that is different from vanilla is the whole point of your package. The specification describes the interface, not the inner workings of an implementation. Otherwise, there would be no need for a standard spec, because there would be only 1 implementation per spec. But we know that this is not that case, and your package is proof of that. "why should extension be necessary" is not your concern, because you cannot ever cater of all the possible ways that someone will use your code. That is why it is pointless to even think about that. Instead, one unit does one thing (SoC), all cases will be covered automatically.

## Pragmatism below
To be completely honest, I didn't come to this issue tracker looking for a way to extend your functionality, but instead I was just trying to gauge how stable this package is. So I stumbled upon this thread, and saw someone's issue, which I resonated with, because this is a common problem of many packages - especially those that try to provide some sort of "comprehensive" solution. So, while I didn't have an example of my own, if the OP saying they _need_ to extend the functionality is not enough (i.e. you simply don't believe them) I have come up with a case.

Or I tried, and even started typing it up, when I realized that the classes have static methods (or at least the main ones are anyway), and cannot be injected. Depending on any interface, even `Session`, is not an option therefore. By consuming a static class, the consumer forever couples themselves to _this specific_ implementation. Due to this limitation,  the only reason to extend this class would be code re-use. But if I were to re-use some of the code in this package, I would do it via copy-paste into a new non-static class anyway in order to prevent such tight coupling. So, yes, in your case having extendable classes doesn't make much sense.

@MrHaroldA, if you want to avoid tight coupling, and consume standards-compliant objects, take a look at [PSR-7][] and compliant implementations, such as [Diactoros][].

[PSR-7]: https://www.php-fig.org/psr/psr-7/
[Diactoros]: https://github.com/zendframework/zend-diactoros

**Comment by MrHaroldA** [comment]
I thought I posted a simple question ;)

Initially, we just wanted to set some hardcoded parameter values in setCookie(), but we also have a custom delete() method which deletes the $_COOKIE entry too, as well as entries starting with the supplied name.

Extending the Cookie-class was by far the easiest option to get all functionality into one (extended) class, so we opted to remove the 'final' declaration. I'd guess other implementations could benefit from this too.

**Comment by XedinUnknown** [comment]
@MrHaroldA, why not use PSR implementations?

**Comment by MrHaroldA** [comment]
I wound't even know how to do that, or if it is possible in our project.

**Comment by ocram** [comment]
Thank you!

You both seem to have ignored that the points were about how *inheritance* may be the wrong tool here, not about this library trying to prevent any modifications or enhancements.

Thanks, @MrHaroldA, for providing the exact use cases, which are really interesting to see and which underline that inheritance is really not necessary here.

Again, inheritance is just one tool in your (OOP) toolbox, and not *the* solution you should just jump to *whenever* you want to modify or augment some code. You should not inject custom business logic into a general-purpose class.

So, let me quickly address your use cases, @MrHaroldA and @XedinUnknown:

You want to hard-code parameters in `Cookie::setcookie` to make your code less verbose? Use composition!

```php
public class MyCookieUtil {
    public static function setcookie($name, $value = null) {
        \Delight\Cookie\Cookie::setcookie($name, $value, 60 * 60 * 24 * 365.2425 * 5, '/', null, true, true, null);
    }
}
```

You want to make `Cookie#delete` remove the `$_COOKIE` entry as well? Use composition!

```php
public class MyCookieUtil {
    public function delete(\Delight\Cookie\Cookie $cookie) {
        $cookie->delete();
        unset($_COOKIE[$cookie->getName()]);
    }
}
```

You want to use PSR-7 (which is definitely not neccesary, but definitely not a bad idea, either)? Again, you can easily use composition here!

```php
public class MyCookieUtil {
    public static function responseWithCookie(\Psr\Http\Message\ResponseInterface $response, \Delight\Cookie\Cookie $cookie) {
        $header = \explode(': ', (string) $cookie);
        return $response->withHeader($header[0], $header[1]);
    }
}
```

**Comment by ocram** [comment]
Oh, and finally:

 * If you encounter a bug or something that needs to be improved or added: Please open an issue here in the issue tracker and help make the bug fix or improvement available to everyone.
 * If you want to change the *implementation* of existing methods without discussing this with others on the issue tracker, perhaps just *fork* this library.

**Comment by XedinUnknown** [comment]
@ocram, you seem to have completely ignored my point, though.

When writing application-level code, [DIP][] dictates that we should depend on abstractions, and not concretions. This means that if I want to make my application adaptable to change, I should depend on some sort of `CookieInterface` that may declare `public function setCookie()`; and that I should inject an implementation of that interface into my class. Doing so guarantees that I will always be able to set a cookie in a meaningful way, while also having the opportunity of altering the mechanism of cookie setting as I see fit. So, if you had the interface as above, even if your class is final and members are private, I could create a decorator, similarly to how you proposed above:

```php
class MyCookie implements CookieInterface
{
	private $cookie;

	public function __construct(CookieInterface $cookie)
	{
		$this->cookie = $cookie;
	}

	public function setCookie($name, $value = null /* etc... */)
	{
		$this->cookie->setCookie($name, $value, 60 * 60 * 24 * 365.2425 * 5, '/', null, true, true, null);
	}
}
```

However, it is impossible to achieve dependency injection with your classes, because they are "static", and therefore cannot be injected. So, depending on their interface (and such some form of an abstraction) is impossible. That's why I wrote that in the case of your classes, having protected members and `final` declaration wouldn't make a difference.

[DIP]: https://en.wikipedia.org/wiki/Dependency_inversion_principle

**Comment by ocram** [comment]
That principle does not mean that you may not call other code directly in the relevant classes that implement that functionality or that you may not write glue code that interacts with other classes.

The interface of the `Cookie` class is exactly what is public from that class. So an additional interface listing those same method signatures would not be helpful, but can certainly be written if one wants to. You can depend on the API of the `Cookie` class, because that’s the interface.

Moreover, the `Cookie` class is not static. You chose to pick the `Cookie::setcookie` method, which has been discussed above and is indeed static, but that’s just because it needs to be static specifically to guarantee compatibility with the PHP core function that it replaces.

**Comment by XedinUnknown** [comment]
> That principle does not mean that you may not call other code directly in the relevant classes that implement that functionality or that you may not write glue code that interacts with other classes.

That's true. It only means that you _should_ follow it **if** you want to make your application adaptable to change. We know that business requirements change, and that this often leads to changes in code. Therefore, it is a good idea to follow that principle.

If you feel that your `Cookie` class is "instance" enough to make it meaningful, then having it not be final, and declaring protected members, is indeed a good idea to give developers more flexibility.
