### ISSUE TITLE
ResponseHeader::take removes all headers with the given name, ignoring the value prefix

### ISSUE THREAD

**Issue by Celos** [delight-im/PHP-Cookie#31]
`ResponseHeader::take` replaces all headers with the given name, not just the one with the given value prefix. 

This presents a problem with the `Set-Cookie` header in particular: Both `Session::regenerate` and `Session::start` use `Session::rewriteCookieHeader` to replace the existing PHPSESSID cookie with the new session ID, which in turn uses `ResponseHeader::take` to grab the  `Set-Cookie` header. That means that by resetting the session or starting a new one, all previous calls to set cookies vanish.

Put another way:
```
Cookie::setcookie('somecookie', 'somevalue', time()+60*60*24*365, '/', null, true, true, Cookie::SAME_SITE_RESTRICTION_NONE);
Session::start();
```
and
```
Session::start();
Cookie::setcookie('somecookie', 'somevalue', time()+60*60*24*365, '/', null, true, true, Cookie::SAME_SITE_RESTRICTION_NONE);
```
produce completely different responses from the server.

**Comment by ocram** [comment]
Thanks a lot, and sorry for the long delay!

It seems the bug was entirely contained in the [HTTP (header) component](https://github.com/delight-im/PHP-HTTP), in the method you mentioned. The wrong behavior should have been fixed in https://github.com/delight-im/PHP-HTTP/commit/46c4db0c4d2a4d83555e04fd2fa9073842d303f1, with tests in https://github.com/delight-im/PHP-HTTP/commit/6f89f68587be99d8b45b792af7b12099b408141a.

You can update that component individually via Composer by running

```bash
$ composer update delight-im/http
```

which should give you (at least) `v2.0.1`. With that fix, this library right here should now work correctly without any further changes.
