### ISSUE TITLE
Secure Defaults

### ISSUE THREAD

**Issue by paragonie-scott** [delight-im/PHP-Cookie#5]
I've forked your project [here](https://github.com/paragonie/PHP-Cookie) with the following changes:

1. Added strict scalar type declarations (PHP 7 only)
2. Made code closer to PSR-2 compliant
3. Changed the defaults to HTTP-Only, Secure, and Same-Site
4. To prevent conflicts, changed the vendor of the forked version.

If you're interested, I can undo the fourth change and send our fork as a pull request, which could be a basis for a version 3.x branch.

**Comment by mwaclawek** [comment]
Thanks a lot!

I'm definitely all for secure defaults and any contributions are welcome. So if you could provide some of your improvements to this repository as well, that would be great.

But let's talk about the points that you mentioned individually:

 1. Regarding scalar type hints, please see https://github.com/delight-im/PHP-Cookie/issues/6 which I just created as a response.
 2. For PSR-2, please see https://github.com/delight-im/PHP-Cookie/issues/7 which I just created as well.
 3. Secure defaults are definitely a good idea. As you can see [here](https://github.com/delight-im/PHP-Cookie/blob/004cde69ec840e65c15275e09b92ecb1da06f357/src/Cookie.php#L57) and [here](https://github.com/delight-im/PHP-Cookie/blob/004cde69ec840e65c15275e09b92ecb1da06f357/src/Cookie.php#L59), "http only" and "same-site" have always been implemented as defaults. But "secure only" cannot be turned on by default because it's less of a no-brainer than the other two options and many sites (unfortunately) are still *not* on HTTPS. In the backwards-compatible `Cookie::setcookie(...)` call, neither of those three options can be turned on by default because that method's very right to exist is ensuring backwards compatibility, which would be broken by *any* of these changes.

I perfectly understand if you want scalar type hints for your own usage of the library, of course.

Again, any changes that would make sense in this general project are definitely welcome!

**Comment by paragonie-scott** [comment]
I sort of expected a "No thanks" because of the breaking-nature of these changes. So thanks for being amicable towards somewhat-radical suggestions. :)

> But "secure only" cannot be turned on by default because it's less of a no-brainer than the other two options and many sites (unfortunately) are still not on HTTPS. 

This is a great point, currently. But it's a temporarily great point. Over the next few years, HTTPS will become the norm. Projects like [Caddy](https://caddyserver.com) will push usable security to the forefront of modern web development and initiatives like the Chrome team are undertaking to mark HTTP pages as **insecure** will change the dynamic significantly.

I believe introducing this change in a new major version of the library that only supports PHP 7+ makes sense, because a project that's likely to use that version is also likely to be more modern (i.e. won't have legacy HTTP-only concerns), as long as it's a documented change.

**Comment by mwaclawek** [comment]
> I sort of expected a "No thanks" because of the breaking-nature of these changes.

No, it's rather a "Thanks, I wish it was possible" ;) For *now*, as you said already. Exclusive PHP 7.0+ support comes closer every day, and HTTPS by default likewise.

> Over the next few years, HTTPS will become the norm. Projects like Caddy will push usable security to the forefront of modern web development and initiatives like the Chrome team are undertaking to mark HTTP pages as insecure will change the dynamic significantly.

Definitely! What a great development. Not to forget Let's Encrypt here, which enables something like Caddy, but makes HTTPS easy on Apache, Nginx, etc. as well.

> I believe introducing this change in a new major version of the library that only supports PHP 7+ makes sense, because a project that's likely to use that version is also likely to be more modern

Ah, that makes sense. Sorry, didn't get that. So your idea is to maintain two separate branches, one for PHP 7.0+ exclusively and one ensuring backwards-compatibility (i.e. the current branch), right?

> Thanks for listening to my feedback. You've done great work.

Thanks, so do you!

**Comment by paragonie-scott** [comment]
> So your idea is to maintain two separate branches, one for PHP 7.0+ exclusively and one ensuring backwards-compatibility (i.e. the current branch), right?

Yep.

If possible, could you link our fork in the README until such a time that a new major version that requires PHP 7 can be considered?

**Comment by ocram** [comment]
To be honest, I see more value in not splitting up development effort and in allowing for consistent and consistently secure usage across supported PHP versions than in adding support for scalar type hints (which are awesome but not critical for security) and defaulting to SSL one or two years earlier.
