### ISSUE TITLE
Integration with HTTPFoundation

### ISSUE THREAD

**Issue by GregMartyn** [delight-im/PHP-Cookie#8]
What integration possibilities are there with HTTPFoundation? Is that something this project would like to explore?

Extend http://api.symfony.com/3.1/Symfony/Component/HttpFoundation/Cookie.html?

Have an alternate addHttpHeader method that accepts a \Symfony\Component\HttpFoundation\Response?

**Comment by mwaclawek** [comment]
Thanks for this proposal!

I have to admit I'm not personally using `Symfony\Component\HttpFoundation`, let alone the `Cookie` class from that package. So I don't really have an idea what could be useful for people using that Symfony component or people using this library.

It seems their cookie class duplicates some of the features from this library, so maybe these two libraries are not complementary but rather mutually exclusive. I don't really know.

Apart from that, it seems they have support for the same-site attribute as well now: https://github.com/symfony/http-foundation/commit/ad11eed7eae097b5097de7c9b5f24d2f2ef416e7

In general, we could probably *extend* their class, as you said, or provide some `fromHttpFoundationCookie` or `toHttpFoundationCookie` methods. But doing that, we would have to require `Symfony\Component\HttpFoundation` as a dependency in this project. Don't know if that's reasonable.

**Comment by GregMartyn** [comment]
I agree; adding that as a dependency would probably be overkill.

Personally I'm interested in HttpFoundation because it will make it easier to write functional tests when the code I'm testing has no global dependencies or side-effects.

The main things that the HttpFoundation Cookie class is missing for me are:

1. Same site support in a released stable version. Having something to bridge that gap would be nice.

2. the addHttpHeader() function. They expect to set the cookie headers with the Response class, but that doesn't yet support same site, and doesn't have a way of sending just the cookie headers. You can't update old code piecemeal by just updating setcookie() calls to Cookie objects like I'm doing; they want you to use the Response class for everything.

Ideally I'd have a class that provided those features, and was forward compatible future versions of HttpFoundation so that I could eventually move to using their Response objects too (and just pass in the Cookie objects that I'd already ported my setcookie() calls to). I'm probably best off just not worrying about HttpFoundation compatibility for now, because it'd be too big an undertaking for the project I'm working on.

Anyway, what I've described does seem like that would be a different library altogether from what this is. Thanks for entertaining the thought though.

**Comment by ocram** [comment]
> Personally I'm interested in `HttpFoundation` because it will make it easier to write functional tests when the code I'm testing has no global dependencies or side-effects.

I absolutely understand this. They encourage you to use their built-in methods instead of global functions such as `header` which send output directly. This library should definitely support their object-oriented style for easier testing of applications.

> Same site support in a released stable version. Having something to bridge that gap would be nice.

Sorry, wasn't aware that it hadn't been included in a release yet!

It had been implemented (but obviously not released) 3.5 months ago. However, we're not going to build some bridge just for the short period until they'll decide to actually release it.

> You can't update old code piecemeal by just updating setcookie() calls to Cookie objects like I'm doing; they want you to use the Response class for everything.

You certainly *can*. It's at least as good as calls to the global function `setcookie` with regard to side effects. They *recommend* something else, but, of course, it's possible to send the cookies without their `Response` class. But it's okay if you don't want to do that -- we should have some workaround.

> I'm probably best off just not worrying about HttpFoundation compatibility for now

Yes, a pragmatic solution would be *not* to use their recommended solution for now, probably.

> Anyway, what I've described does seem like that would be a different library altogether from what this is.

Well, actually this library does everything you need -- and even much more than the respective class from `HttpFoundation`. The only issue is, as we've seen, that their `Response` class won't accept our cookie instances.

Anyway, what about the following workaround for now, which should work *today*?

```php
// `$response` is *their* `Response` instance
// `$cookie ` is *our* `Cookie` instance

$cookieStr = explode(': ', (string) $cookie);
$response->headers->set($cookieStr[0], $cookieStr[0]);
```

This works today! It gets the `ResponseHeaderBag` from the `Response` class of `HttpFoundation` and adds the value built by our cookie instance. This should work fine and still uses *their* solution without side effects.

The extra work is necessary because we only provide access to the full HTTP header for the cookie, i.e. name and value combined. If we added two new methods, e.g. `getHeaderName` and `getHeaderValue`, to retrieve them separately, you could simply write the following instead of what's shown above:

```php
$response->headers->set($cookie->getHeaderName(), $cookie->getHeaderValue());
```

It's a solution that uses the improved cookies from this library but still uses `HttpFoundation` to set them, which is equivalent to calling `header`, but regarded as better style.

**Comment by ocram** [comment]
Symfony is working on release candidates for version 3.2 right now. So that release will ship soon -- and it will include support for the same-site restriction, as far as I know.

Apart from that, the (ugly) workaround that I've shown above can be used, and there is still the potential for the more elegant workaround shown below the other one.

**Comment by ocram** [comment]
Symfony 3.2 [has been available](https://symfony.com/blog/symfony-3-2-0-released) since November 30 now and includes the updated version of HttpFoundation which supports the same-site attribute.

Thus this issue here is obsolete now, but we should still break up `buildCookieHeader` into two separate accessors, which would have helped here as well. We'll track this in https://github.com/delight-im/PHP-Cookie/issues/14
